# Generated by Django 4.2.3 on 2023-07-31 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('executive_app', '0002_entrancescan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrancescan',
            name='Executive',
        ),
    ]
