# Generated by Django 4.2.3 on 2023-07-31 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('executive_app', '0003_remove_entrancescan_executive'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancescan',
            name='Executive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='executive_app.executives'),
        ),
    ]
