# Generated by Django 4.2.3 on 2023-07-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstore',
            name='app_logo',
            field=models.FileField(blank=True, null=True, upload_to='AppStore/'),
        ),
    ]
