# Generated by Django 4.2.3 on 2023-07-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitor_app', '0002_alter_exhibitors_boothnumber_alter_exhibitors_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibitors',
            old_name='conatctemail',
            new_name='contactemail',
        ),
        migrations.RenameField(
            model_name='exhibitors',
            old_name='conatctnumber',
            new_name='contactnumber',
        ),
        migrations.RenameField(
            model_name='exhibitors',
            old_name='conatctperson',
            new_name='contactperson',
        ),
    ]
