# Generated by Django 4.2.3 on 2023-07-28 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
        ('exhibitor_app', '0003_rename_conatctemail_exhibitors_contactemail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoothVisitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ID', models.CharField(max_length=240, null=True)),
                ('visited_DT', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(default='0', max_length=240)),
                ('Booth', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exhibitor_app.exhibitors')),
                ('visitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_app.student_registration')),
            ],
        ),
    ]
